//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_EVALUACION
    {
        public decimal ID_DETALLE_EVALUACION { get; set; }
        public Nullable<decimal> ID_EVALUACION { get; set; }
        public Nullable<decimal> ID_PERIODO_EVALUACION { get; set; }
        public string RUT { get; set; }
        public Nullable<decimal> NOTA_AUTOEVALUACION { get; set; }
        public Nullable<decimal> NOTA_EVALUACION { get; set; }
        public Nullable<decimal> NOTA_FINAL { get; set; }
        public Nullable<decimal> BRECHA { get; set; }
    
        public virtual EVALUACION EVALUACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PERIODO_EVALUACION PERIODO_EVALUACION { get; set; }
    }
}
