//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO_EVALUACION
    {
        public PERIODO_EVALUACION()
        {
            this.DETALLE_EVALUACION = new HashSet<DETALLE_EVALUACION>();
            this.EVALUACION = new HashSet<EVALUACION>();
        }
    
        public decimal ID_PERIODO_EVALUACION { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public decimal VIGENCIA { get; set; }
    
        public virtual ICollection<DETALLE_EVALUACION> DETALLE_EVALUACION { get; set; }
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
    }
}
