//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.DETALLE_EVALUACION = new HashSet<DETALLE_EVALUACION>();
        }
    
        public string RUT { get; set; }
        public Nullable<decimal> ID_AREA { get; set; }
        public Nullable<decimal> ID_PERFIL { get; set; }
        public string NOMBRE { get; set; }
        public string SEXO { get; set; }
        public string JEFE_RESPECTIVO { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual ICollection<DETALLE_EVALUACION> DETALLE_EVALUACION { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
